// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserPasswords(arg1:string):Promise<{[key: string]: string}>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SaveUserPassword(arg1:string,arg2:string,arg3:string):Promise<void>;
