// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bbolt} from '../models';
import {models} from '../models';
import {time} from '../models';

export function DeletePassword(arg1:string,arg2:string):Promise<void>;

export function GetUserPasswords(arg1:string):Promise<{[key: string]: string}>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListUsers(arg1:Array<string>,arg2:string,arg3:bbolt.DB):Promise<Array<models.User>>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function PasswordGenerator(arg1:number):Promise<string|string>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SaveUserPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StoreSessionToken(arg1:string,arg2:string,arg3:time.Time):Promise<void>;

export function VerifySessionToken(arg1:string):Promise<boolean>;
