// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePassword(arg1, arg2) {
  return window['go']['main']['App']['DeletePassword'](arg1, arg2);
}

export function GetUserPasswords(arg1) {
  return window['go']['main']['App']['GetUserPasswords'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListUsers'](arg1, arg2, arg3);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function PasswordGenerator(arg1) {
  return window['go']['main']['App']['PasswordGenerator'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SaveUserPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveUserPassword'](arg1, arg2, arg3);
}

export function StoreSessionToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['StoreSessionToken'](arg1, arg2, arg3);
}

export function VerifySessionToken(arg1) {
  return window['go']['main']['App']['VerifySessionToken'](arg1);
}
