// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DoDeleteUserPassword(arg1:string,arg2:string):Promise<void>;

export function DoLogin(arg1:string,arg2:string):Promise<string>;

export function DoRegister(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DoSaveUserPassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetListUsers(arg1:Array<string>,arg2:string):Promise<Array<models.User>>;

export function GetTokenVerification(arg1:string):Promise<boolean>;

export function GetUserPasswords(arg1:string):Promise<{[key: string]: string}>;

export function GetVersion():Promise<string>;

export function PasswordGenerator(arg1:number):Promise<string|string>;

export function ShowPassword(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestGreet(arg1:string):Promise<string>;
