// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCard(arg1, arg2) {
  return window['go']['app']['App']['DeleteCard'](arg1, arg2);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['app']['App']['DeleteGroup'](arg1, arg2);
}

export function DoChangeAccountInfo(arg1, arg2) {
  return window['go']['app']['App']['DoChangeAccountInfo'](arg1, arg2);
}

export function DoChangeAccountPassword(arg1, arg2, arg3) {
  return window['go']['app']['App']['DoChangeAccountPassword'](arg1, arg2, arg3);
}

export function DoCheckSeeds(arg1) {
  return window['go']['app']['App']['DoCheckSeeds'](arg1);
}

export function DoDeletePassword(arg1, arg2) {
  return window['go']['app']['App']['DoDeletePassword'](arg1, arg2);
}

export function DoExport(arg1, arg2) {
  return window['go']['app']['App']['DoExport'](arg1, arg2);
}

export function DoImport(arg1) {
  return window['go']['app']['App']['DoImport'](arg1);
}

export function DoLogin(arg1) {
  return window['go']['app']['App']['DoLogin'](arg1);
}

export function DoLogout() {
  return window['go']['app']['App']['DoLogout']();
}

export function DoNewCard(arg1, arg2) {
  return window['go']['app']['App']['DoNewCard'](arg1, arg2);
}

export function DoNewGroup(arg1, arg2) {
  return window['go']['app']['App']['DoNewGroup'](arg1, arg2);
}

export function DoNewPassword(arg1, arg2, arg3) {
  return window['go']['app']['App']['DoNewPassword'](arg1, arg2, arg3);
}

export function DoRecovery(arg1) {
  return window['go']['app']['App']['DoRecovery'](arg1);
}

export function DoRegister(arg1) {
  return window['go']['app']['App']['DoRegister'](arg1);
}

export function DoSetPasswordSettings(arg1, arg2, arg3) {
  return window['go']['app']['App']['DoSetPasswordSettings'](arg1, arg2, arg3);
}

export function DoUpdatePassword(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DoUpdatePassword'](arg1, arg2, arg3, arg4);
}

export function GetAccountInfo(arg1) {
  return window['go']['app']['App']['GetAccountInfo'](arg1);
}

export function GetAllCards(arg1) {
  return window['go']['app']['App']['GetAllCards'](arg1);
}

export function GetAllCredentialsByGroup(arg1, arg2) {
  return window['go']['app']['App']['GetAllCredentialsByGroup'](arg1, arg2);
}

export function GetAllPasswords(arg1) {
  return window['go']['app']['App']['GetAllPasswords'](arg1);
}

export function GetCardById(arg1, arg2) {
  return window['go']['app']['App']['GetCardById'](arg1, arg2);
}

export function GetGroups(arg1) {
  return window['go']['app']['App']['GetGroups'](arg1);
}

export function GetLastSession() {
  return window['go']['app']['App']['GetLastSession']();
}

export function GetListAccounts() {
  return window['go']['app']['App']['GetListAccounts']();
}

export function GetPasswordById(arg1, arg2) {
  return window['go']['app']['App']['GetPasswordById'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function PasswordDecrypt(arg1, arg2, arg3) {
  return window['go']['app']['App']['PasswordDecrypt'](arg1, arg2, arg3);
}

export function TestGreet(arg1) {
  return window['go']['app']['App']['TestGreet'](arg1);
}

export function UpdateCard(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateCard'](arg1, arg2, arg3);
}

export function VerifyToken(arg1) {
  return window['go']['app']['App']['VerifyToken'](arg1);
}
