// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoChangeAccountInfo(arg1, arg2) {
  return window['go']['app']['App']['DoChangeAccountInfo'](arg1, arg2);
}

export function DoChangeAccountPassword(arg1, arg2, arg3) {
  return window['go']['app']['App']['DoChangeAccountPassword'](arg1, arg2, arg3);
}

export function DoDeleteUserPassword(arg1, arg2) {
  return window['go']['app']['App']['DoDeleteUserPassword'](arg1, arg2);
}

export function DoLogin(arg1, arg2) {
  return window['go']['app']['App']['DoLogin'](arg1, arg2);
}

export function DoLogout() {
  return window['go']['app']['App']['DoLogout']();
}

export function DoRegister(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DoRegister'](arg1, arg2, arg3, arg4);
}

export function DoSaveUserPassword(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['DoSaveUserPassword'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DoSetPasswordConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['DoSetPasswordConfig'](arg1, arg2, arg3);
}

export function DoUpdateUserPassword(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['DoUpdateUserPassword'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetLastSession() {
  return window['go']['app']['App']['GetLastSession']();
}

export function GetListUsers() {
  return window['go']['app']['App']['GetListUsers']();
}

export function GetUserInfo(arg1) {
  return window['go']['app']['App']['GetUserInfo'](arg1);
}

export function GetUserPasswordById(arg1, arg2) {
  return window['go']['app']['App']['GetUserPasswordById'](arg1, arg2);
}

export function GetUserPasswords(arg1) {
  return window['go']['app']['App']['GetUserPasswords'](arg1);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function ShowPassword(arg1, arg2, arg3) {
  return window['go']['app']['App']['ShowPassword'](arg1, arg2, arg3);
}

export function TestGreet(arg1) {
  return window['go']['app']['App']['TestGreet'](arg1);
}

export function VerifyToken(arg1) {
  return window['go']['app']['App']['VerifyToken'](arg1);
}
