// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoChangeUserPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DoDeleteUserPassword(arg1:string,arg2:string):Promise<void>;

export function DoLogin(arg1:string,arg2:string):Promise<string>;

export function DoRegister(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DoSaveUserPassword(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DoUpdateUserPassword(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function GetListUsers():Promise<string>;

export function GetTokenVerification(arg1:string):Promise<boolean>;

export function GetUserInfo(arg1:string):Promise<string>;

export function GetUserPasswords(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function PasswordGenerator(arg1:number):Promise<string>;

export function ShowPassword(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestGreet(arg1:string):Promise<string>;
