// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {request} from '../models';
import {response} from '../models';

export function DeleteCard(arg1:string,arg2:string):Promise<void>;

export function DeleteGroup(arg1:string,arg2:string):Promise<void>;

export function DoChangeAccountInfo(arg1:string,arg2:models.UserRequest):Promise<void>;

export function DoChangeAccountPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DoCheckSeeds(arg1:request.SeedsCheck):Promise<void>;

export function DoDeletePassword(arg1:string,arg2:string):Promise<void>;

export function DoLogin(arg1:request.Login):Promise<response.Login>;

export function DoLogout():Promise<void>;

export function DoNewCard(arg1:string,arg2:request.Card):Promise<string>;

export function DoNewGroup(arg1:string,arg2:Array<string>):Promise<void>;

export function DoNewPassword(arg1:string,arg2:string,arg3:request.Password):Promise<string>;

export function DoRecovery(arg1:request.Recovery):Promise<void>;

export function DoRegister(arg1:request.Register):Promise<response.Register>;

export function DoSetPasswordSettings(arg1:string,arg2:string,arg3:models.Settings):Promise<void>;

export function DoUpdatePassword(arg1:string,arg2:string,arg3:string,arg4:request.Password):Promise<void>;

export function GetAccountInfo(arg1:string):Promise<string>;

export function GetAllCards(arg1:string):Promise<Array<models.Card>>;

export function GetAllPasswords(arg1:string):Promise<Array<models.Password>>;

export function GetCardById(arg1:string,arg2:string):Promise<models.Card>;

export function GetGroups(arg1:string):Promise<Array<string>>;

export function GetLastSession():Promise<string>;

export function GetListAccounts():Promise<Array<models.User>>;

export function GetPasswordById(arg1:string,arg2:string):Promise<models.Password>;

export function GetVersion():Promise<string>;

export function PasswordDecrypt(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestGreet(arg1:string):Promise<string>;

export function UpdateCard(arg1:string,arg2:string,arg3:request.Card):Promise<void>;

export function VerifyToken(arg1:string):Promise<boolean>;
